// This file was automatically generated by lister-gen with arguments: --go-header-file=/home/deads/workspaces/o-kube-aggregator/src/github.com/openshift/kube-aggregator/hack/boilerplate.txt --input-dirs=[github.com/openshift/kube-aggregator/pkg/apis/apifederation,github.com/openshift/kube-aggregator/pkg/apis/apifederation/v1beta1] --output-package=github.com/openshift/kube-aggregator/pkg/client/listers

package internalversion

import (
	apifederation "github.com/openshift/kube-aggregator/pkg/apis/apifederation"
	api "k8s.io/kubernetes/pkg/api"
	"k8s.io/kubernetes/pkg/api/errors"
	"k8s.io/kubernetes/pkg/client/cache"
	"k8s.io/kubernetes/pkg/labels"
)

// APIServerLister helps list APIServers.
type APIServerLister interface {
	// List lists all APIServers in the indexer.
	List(selector labels.Selector) (ret []*apifederation.APIServer, err error)
	// Get retrieves the APIServer from the index for a given name.
	Get(name string) (*apifederation.APIServer, error)
	APIServerListerExpansion
}

// aPIServerLister implements the APIServerLister interface.
type aPIServerLister struct {
	indexer cache.Indexer
}

// NewAPIServerLister returns a new APIServerLister.
func NewAPIServerLister(indexer cache.Indexer) APIServerLister {
	return &aPIServerLister{indexer: indexer}
}

// List lists all APIServers in the indexer.
func (s *aPIServerLister) List(selector labels.Selector) (ret []*apifederation.APIServer, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*apifederation.APIServer))
	})
	return ret, err
}

// Get retrieves the APIServer from the index for a given name.
func (s *aPIServerLister) Get(name string) (*apifederation.APIServer, error) {
	key := &apifederation.APIServer{ObjectMeta: api.ObjectMeta{Name: name}}
	obj, exists, err := s.indexer.Get(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(apifederation.Resource("apiserver"), name)
	}
	return obj.(*apifederation.APIServer), nil
}
