// This file was automatically generated by lister-gen with arguments: --go-header-file=/home/deads/workspaces/o-kube-aggregator/src/github.com/openshift/kube-aggregator/hack/boilerplate.txt --input-dirs=[github.com/openshift/kube-aggregator/pkg/apis/apifederation,github.com/openshift/kube-aggregator/pkg/apis/apifederation/v1beta1] --output-package=github.com/openshift/kube-aggregator/pkg/client/listers

package internalversion

// APIServerListerExpansion allows custom methods to be added to
// APIServerLister.
type APIServerListerExpansion interface{}
