// This package is generated by client-gen with arguments: --clientset-path=github.com/openshift/kube-aggregator/pkg/apis/pkg/client/clientset_generated --go-header-file=/home/deads/workspaces/o-kube-aggregator/src/github.com/openshift/kube-aggregator/hack/boilerplate.txt --input=[apifederation/] --input-base=github.com/openshift/kube-aggregator/pkg/apis

// This package has the automatically generated fake clientset.
package fake
