// +build !ignore_autogenerated_openshift

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1beta1

import (
	api "github.com/openshift/kube-aggregator/pkg/api"
	pkg_api "k8s.io/kubernetes/pkg/api"
	v1 "k8s.io/kubernetes/pkg/api/v1"
	conversion "k8s.io/kubernetes/pkg/conversion"
	runtime "k8s.io/kubernetes/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1beta1_APIResource_To_api_APIResource,
		Convert_api_APIResource_To_v1beta1_APIResource,
		Convert_v1beta1_APIServer_To_api_APIServer,
		Convert_api_APIServer_To_v1beta1_APIServer,
		Convert_v1beta1_APIServerCondition_To_api_APIServerCondition,
		Convert_api_APIServerCondition_To_v1beta1_APIServerCondition,
		Convert_v1beta1_APIServerList_To_api_APIServerList,
		Convert_api_APIServerList_To_v1beta1_APIServerList,
		Convert_v1beta1_APIServerSpec_To_api_APIServerSpec,
		Convert_api_APIServerSpec_To_v1beta1_APIServerSpec,
		Convert_v1beta1_APIServerStatus_To_api_APIServerStatus,
		Convert_api_APIServerStatus_To_v1beta1_APIServerStatus,
		Convert_v1beta1_APISubResource_To_api_APISubResource,
		Convert_api_APISubResource_To_v1beta1_APISubResource,
	)
}

func autoConvert_v1beta1_APIResource_To_api_APIResource(in *APIResource, out *api.APIResource, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespaced = in.Namespaced
	out.Kind = in.Kind
	out.SubResources = *(*[]api.APISubResource)(unsafe.Pointer(&in.SubResources))
	return nil
}

func Convert_v1beta1_APIResource_To_api_APIResource(in *APIResource, out *api.APIResource, s conversion.Scope) error {
	return autoConvert_v1beta1_APIResource_To_api_APIResource(in, out, s)
}

func autoConvert_api_APIResource_To_v1beta1_APIResource(in *api.APIResource, out *APIResource, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespaced = in.Namespaced
	out.Kind = in.Kind
	out.SubResources = *(*[]APISubResource)(unsafe.Pointer(&in.SubResources))
	return nil
}

func Convert_api_APIResource_To_v1beta1_APIResource(in *api.APIResource, out *APIResource, s conversion.Scope) error {
	return autoConvert_api_APIResource_To_v1beta1_APIResource(in, out, s)
}

func autoConvert_v1beta1_APIServer_To_api_APIServer(in *APIServer, out *api.APIServer, s conversion.Scope) error {
	if err := v1.Convert_v1_ObjectMeta_To_api_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_APIServerSpec_To_api_APIServerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_APIServerStatus_To_api_APIServerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func Convert_v1beta1_APIServer_To_api_APIServer(in *APIServer, out *api.APIServer, s conversion.Scope) error {
	return autoConvert_v1beta1_APIServer_To_api_APIServer(in, out, s)
}

func autoConvert_api_APIServer_To_v1beta1_APIServer(in *api.APIServer, out *APIServer, s conversion.Scope) error {
	if err := v1.Convert_api_ObjectMeta_To_v1_ObjectMeta(&in.ObjectMeta, &out.ObjectMeta, s); err != nil {
		return err
	}
	if err := Convert_api_APIServerSpec_To_v1beta1_APIServerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_api_APIServerStatus_To_v1beta1_APIServerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

func Convert_api_APIServer_To_v1beta1_APIServer(in *api.APIServer, out *APIServer, s conversion.Scope) error {
	return autoConvert_api_APIServer_To_v1beta1_APIServer(in, out, s)
}

func autoConvert_v1beta1_APIServerCondition_To_api_APIServerCondition(in *APIServerCondition, out *api.APIServerCondition, s conversion.Scope) error {
	out.Type = api.APIServerConditionType(in.Type)
	out.Status = pkg_api.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

func Convert_v1beta1_APIServerCondition_To_api_APIServerCondition(in *APIServerCondition, out *api.APIServerCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_APIServerCondition_To_api_APIServerCondition(in, out, s)
}

func autoConvert_api_APIServerCondition_To_v1beta1_APIServerCondition(in *api.APIServerCondition, out *APIServerCondition, s conversion.Scope) error {
	out.Type = APIServerConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastProbeTime = in.LastProbeTime
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

func Convert_api_APIServerCondition_To_v1beta1_APIServerCondition(in *api.APIServerCondition, out *APIServerCondition, s conversion.Scope) error {
	return autoConvert_api_APIServerCondition_To_v1beta1_APIServerCondition(in, out, s)
}

func autoConvert_v1beta1_APIServerList_To_api_APIServerList(in *APIServerList, out *api.APIServerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]api.APIServer, len(*in))
		for i := range *in {
			if err := Convert_v1beta1_APIServer_To_api_APIServer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

func Convert_v1beta1_APIServerList_To_api_APIServerList(in *APIServerList, out *api.APIServerList, s conversion.Scope) error {
	return autoConvert_v1beta1_APIServerList_To_api_APIServerList(in, out, s)
}

func autoConvert_api_APIServerList_To_v1beta1_APIServerList(in *api.APIServerList, out *APIServerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIServer, len(*in))
		for i := range *in {
			if err := Convert_api_APIServer_To_v1beta1_APIServer(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

func Convert_api_APIServerList_To_v1beta1_APIServerList(in *api.APIServerList, out *APIServerList, s conversion.Scope) error {
	return autoConvert_api_APIServerList_To_v1beta1_APIServerList(in, out, s)
}

func autoConvert_v1beta1_APIServerSpec_To_api_APIServerSpec(in *APIServerSpec, out *api.APIServerSpec, s conversion.Scope) error {
	out.Group = in.Group
	out.Version = in.Version
	out.InternalHost = in.InternalHost
	out.Prefix = in.Prefix
	out.Priority = in.Priority
	return nil
}

func Convert_v1beta1_APIServerSpec_To_api_APIServerSpec(in *APIServerSpec, out *api.APIServerSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_APIServerSpec_To_api_APIServerSpec(in, out, s)
}

func autoConvert_api_APIServerSpec_To_v1beta1_APIServerSpec(in *api.APIServerSpec, out *APIServerSpec, s conversion.Scope) error {
	out.InternalHost = in.InternalHost
	out.Prefix = in.Prefix
	out.Group = in.Group
	out.Version = in.Version
	out.Priority = in.Priority
	return nil
}

func Convert_api_APIServerSpec_To_v1beta1_APIServerSpec(in *api.APIServerSpec, out *APIServerSpec, s conversion.Scope) error {
	return autoConvert_api_APIServerSpec_To_v1beta1_APIServerSpec(in, out, s)
}

func autoConvert_v1beta1_APIServerStatus_To_api_APIServerStatus(in *APIServerStatus, out *api.APIServerStatus, s conversion.Scope) error {
	out.Group = in.Group
	out.Version = in.Version
	out.Resources = *(*[]api.APIResource)(unsafe.Pointer(&in.Resources))
	out.Conditions = *(*[]api.APIServerCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

func Convert_v1beta1_APIServerStatus_To_api_APIServerStatus(in *APIServerStatus, out *api.APIServerStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_APIServerStatus_To_api_APIServerStatus(in, out, s)
}

func autoConvert_api_APIServerStatus_To_v1beta1_APIServerStatus(in *api.APIServerStatus, out *APIServerStatus, s conversion.Scope) error {
	out.Conditions = *(*[]APIServerCondition)(unsafe.Pointer(&in.Conditions))
	out.Group = in.Group
	out.Version = in.Version
	out.Resources = *(*[]APIResource)(unsafe.Pointer(&in.Resources))
	return nil
}

func Convert_api_APIServerStatus_To_v1beta1_APIServerStatus(in *api.APIServerStatus, out *APIServerStatus, s conversion.Scope) error {
	return autoConvert_api_APIServerStatus_To_v1beta1_APIServerStatus(in, out, s)
}

func autoConvert_v1beta1_APISubResource_To_api_APISubResource(in *APISubResource, out *api.APISubResource, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	return nil
}

func Convert_v1beta1_APISubResource_To_api_APISubResource(in *APISubResource, out *api.APISubResource, s conversion.Scope) error {
	return autoConvert_v1beta1_APISubResource_To_api_APISubResource(in, out, s)
}

func autoConvert_api_APISubResource_To_v1beta1_APISubResource(in *api.APISubResource, out *APISubResource, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	return nil
}

func Convert_api_APISubResource_To_v1beta1_APISubResource(in *api.APISubResource, out *APISubResource, s conversion.Scope) error {
	return autoConvert_api_APISubResource_To_v1beta1_APISubResource(in, out, s)
}
